name: Create Tag

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Fetch All tags
        run: git fetch --tags
        
      - name: Get Latest Version
        id: get_latest_tag
        run: git describe --abbrev=0 --tags >> $GITHUB_OUTPUT
        
      - name: Print State
        run: echo $GITHUB_OUTPUT

      - name: New Tag Version
        id: generate_new_tag
        run: echo ::set-output name=tag::$(python increment_version.py ${{ steps.get_latest_tag.outputs.tag }})

      - name: Create Tag
        run: git tag ${{ steps.generate_new_tag.outputs.tag }}

      - name: Push new tag
        run: git push origin --tags
